### ISSUE TITLE
Copyright Wording makes Haiku Porter Fail

### ISSUE THREAD

**Issue by agmsmith** [haikuports/haikuporter#101]
Add the word "Copyright" in front of a copyright notice, for example in the "which" recipe change the text from:

COPYRIGHT="Free Software Foundation"
to
COPYRIGHT="Copyright Free Software Foundation"

and then any invocation (even to build something else) of HaikuPorter will fail with an error saying:
'ascii' coded can't decode byte 0xc2 in position 50: ordinal not in range(128)

Not the most helpful error message!

**Comment by mmuman** [comment]
try doing this before calling it:
export LC_ALL=en_US.UTF-8

This should make sure Python accepts UTF-8 as input.

**Comment by mmuman** [comment]
Although the COPYRIGHT shouldn't mention the word anyway.

**Comment by agmsmith** [comment]
Nope, changing the locale to en_US.UTF-8 doesn't fix it.  I had thought it was a bad UTF-8 character from copying and pasting the copyright notice text, but even retyping it as plain ASCII still makes the bug happen.  Just typing in that word in any existing recipe makes it fail.

**Comment by waddlesplash** [comment]
OH, I have a guess of what's going wrong here. Will investigate when I have time.

**Comment by pulkomandy** [comment]
The word "copyright" is not allowed. Detecting it and failing works. What fails is showing the error message, which indeed also contains an UTF8 copyright sign. And instead of the expected error message you get a cryptical error about UTF8 codecs and stuff.

**Comment by mmuman** [comment]
That's because python2 still thinks the console is ASCII7 by default.
If setting LC_ALL doesn't work, maybe LC_CTYPE or LANG would work ?

**Comment by agmsmith** [comment]
Tried all of those LC_ varieties and it still doesn't work.

**Comment by agmsmith** [comment]
Ran into a similar error further along the build, but this time I had --debug as a HaikuPorter argument and the stack trace ended with:

  File "/boot/home/haikuporter/HaikuPorter/SourceFetcher.py", line 87, in unpackFile
    unpackArchive(fetchTarget, sourceBaseDir, actualSubDir)
  File "/boot/home/haikuporter/HaikuPorter/Utils.py", line 139, in unpackArchive
    if os.path.normpath(name).startswith(subdir)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 24: ordinal not in range(128)

**Comment by fbrosson** [comment]
When I have these kind of errors I just source a script (that I have named pyutf) which does:
```
PYTHONIOENCODING=utf-8
export PYTHONIOENCODING
```
I wonder if this would help haikuporter to display the correct error message when the word copyright is in COPYRIGHT.
Well,  I can test it myself!!! ;-)

**Comment by agmsmith** [comment]
Well, this latest mystery error message has something to do with the source code being two directories deep within a .zip file, "BeShare/source" seems to confuse HaikuPorters source extractor.  Though it also looks like bad code there in Utils.py line 139 for .zip files, but I'm not a Python programmer.

**Comment by mmuman** [comment]
Ah yes, PYTHONIOENCODING, I remembered having to export something but that one was not usual :)

**Comment by agmsmith** [comment]
One more clue, I've got my locale set to Canadian English, so the LC environment looks like this:  env | grep LC
LC_MONETARY=en_CA.UTF-8
LC_NUMERIC=en_CA.UTF-8
LC_TYPE=en_US.UTF-8
LC_MESSAGES=en_CA.UTF-8
LC_COLLATE=en_CA.UTF-8
LC_CTYPE=en_CA.UTF-8
LC_TIME=en_CA.UTF-8

Though changing them all to en_US.UTF-8 doesn't fix it.

Nor does PYTHONIOENCODING help, the error message changes to "LookupError: unknown encoding: en_US.UTF-8" with a different stack backtrace in that case, or if I set it to UTF-8, the original decoding error happens.

**Comment by jessicah** [comment]
That's a terrible change. Our terminal handles utf-8 just fine.

**Comment by waddlesplash** [comment]
Well, if you know how to get Python to print UTF-8 characters to stdout without barfing, be my guest...

**Comment by jessicah** [comment]
I shall work on this

**Comment by mmuman** [comment]
See http://stackoverflow.com/questions/11741574/how-to-print-utf-8-encoded-text-to-the-console-in-python-3 IIRC it worked when I tried.

**Comment by jessicah** [comment]
Printing utf-8 text to console works perfectly fine. Just tidying up my patch now.

**Comment by jessicah** [comment]
Fixed in c0f87dc & 71a83f9.
