### ISSUE TITLE
Tarballs don't work

### ISSUE THREAD

**Issue by ohnx** [haikuports/haikuporter#106]
Tarballs don't seem to work with HaikuPorter - when you decompress them, they are empty.

Possibly caused by 25dd75443198af3c4782ff270e36d43799414a45 or 24e576ba78764d9724d3097aefb9950e22f83683.

**Comment by pulkomandy** [comment]
This can happen if your SOURCE_DIR is incorrect. Did you check that? (it must match the root directory of the archive).

**Comment by ohnx** [comment]
I list the files in the extracted directory, and it is empty.

**Comment by ohnx** [comment]
Ok, so I tried again and it works now...

Not sure what caused the problem originally.
