### ISSUE TITLE
Support patches with multiple SOURCE_URI entries

### ISSUE THREAD

**Issue by static-void** [haikuports/haikuporter#118]
The openjdk recipe (openjdk-1.7.u80_b32) has multiple SOURCE_URI entries. It also supplies a patch, which should be applied to SOURCE_URI_9 and this is indicated in the patch name: openjdk_x86-1.7-1.7.u80_b32-source9.patchset (note the -source9 suffix).

haikuporter currently fails to apply this patch, attempting to apply it just after initialising the git repo in work-xxx/sources directory. The failure is due to having not initialised a git repo in the work-xxx/sources-9 folder. If the patch is removed from the recipe, haikuporter does initialiase an empty git repo. So there appears to be an ordering dependency that is not respected (it should initiaslise the repo before applying the patch, not after).

However, I would also suggest that an improvement might be to, instead of adding a suffix to patch names (-sourceX.patchset), have the recipe includes a "PATCHES_X" entry instead, that matches the "SOURCE_URI_X" entry. This seems clearer to me in terms of what I as an end user would expect, but I am not sure if everyone will be happy with how it works with respect to automatic patch generation by haikuporter, so perhaps it is better to just to fix the problem.

**Comment by static-void** [comment]
Looking a bit more, I'm not exactly sure my synopsis above is completely accurate in terms of the order of things being done being wrong, but I'll leave that up to the experts ;)

**Comment by korli** [comment]
This is already supported: see for instance https://github.com/haikuports/haikuports/blob/master/dev-qt/qt5/qt5-5.7.1.recipe#L11
The recipe was likely broken in https://github.com/haikuports/haikuports/commit/a3a757aa7579349d6d2ff5138ca9b3935b5384eb.
You can open a PR for a fix at the haikuports repository. Thanks. I'm closing this issue.

**Comment by static-void** [comment]
hah, thanks. I'll give that a try and see how it goes. If it works I can manage a pull request ;)
