### ISSUE TITLE
buildslave stuck on interactive prompt

### ISSUE THREAD

**Issue by pulkomandy** [haikuports/haikuporter#125]
While running in buildmaster mode, a buildslave can be stuck waiting on an interactive prompt.
For example, when trying to build an unsupported package. After manually killing bash on the slave, we get this in the log:

    Warning: Port libvpx_x86-1.0.0 is broken on this architecture.
    Continue (y/n + enter)?

Why did the slave get to build this, if it is not supported after all?

**Comment by pulkomandy** [comment]
I think this was caused by the build slave having local changes in the git checkout. We checkout a specific revision but do not check that the working directory is clean, maybe this should be added.

**Comment by scottmc** [comment]
Something like this:
If in buildslave mode, check if clean, if not clean, then clean before building.

 Or perhaps if in buildslave mode and build directory  Is not empty just rename the current directory, and create an empty new build directory so no work is lost, just moved.

**Comment by pulkomandy** [comment]
In this case, it is not the build directory, but the main git checkout of haikuporter. I had a modified recipe there on the buildslave, and it was used instead of the one in the repository.

I think there is already a clean of the port work directory for buildslaves.

**Comment by pulkomandy** [comment]
Well I think the new buildslaves are working fine and are better managed.
