### ISSUE TITLE
Improve error reporting when SOURCE_DIR is wrong

### ISSUE THREAD

**Issue by diversys** [haikuports/haikuporter#143]
Current output doesn't tell what might be wrong and just fail to git commit.
```
2017-11-06 13:10:47 (653 KB/s) - ‘/boot/home/workbench/haikuports/dev-lang/scala/download/scala-2.6.0-final.tar.gz’ saved [13535849/13535849]
Validating checksum of scala-2.6.0-final.tar.gz
Unpacking source of scala-2.6.0-final.tar.gz
Initialized empty Git repository in /boot/home/workbench/haikuports/dev-lang/scala/work-2.6.0/sources/scala/.git/
Command '['git', 'commit', '-m', 'import', '-q']' returned non-zero exit status 1
```

**Comment by kallisti5** [comment]
Indeed. Just ran into this as well.  Really annoying.

![missing_source_directory](https://user-images.githubusercontent.com/100110/37170312-24e22cae-22d0-11e8-8da4-20683e0fb96d.png)


We need:
  * Check for SOURCE_DIR
  * Recommend SOURCE_DIR when it doesn't exist.
 
Example Error:
  "$SOURCE_DIR wasn't found in source archive, maybe SOURCE_DIR needs adjusted in recipe?"

**Comment by kallisti5** [comment]
resolved via commit above.
