### ISSUE TITLE
defineDebugInfoPackage: avoid using sed.

### ISSUE THREAD

**Issue by korli** [haikuports/haikuporter#152]
https://github.com/haikuports/haikuporter/commit/9b910e2f9ef289b4d2958de37cf15b51d6236622#commitcomment-26057084

> Seems like defineDebugInfoPackage requires sed, which might not be available by recipe evaluation.
Better would be to replace sed with bash in:
https://github.com/haikuports/haikuporter/blob/master/HaikuPorter/ShellScriptlets.py#L145

> local entityName=$(basename $path)
> entityName=${entityName//-/_}

**Comment by KapiX** [comment]
I'll take care of this on weekend.
