### ISSUE TITLE
Buildmaster install needs to be updated

### ISSUE THREAD

**Issue by waddlesplash** [haikuports/haikuporter#166]
The new ca_root_certificates build failed: https://eu.hpkg.haiku-os.org/buildmaster/master/x86_gcc2/buildruns/1631/builds/28824.log This was already fixed in https://github.com/haikuports/haikuporter/commit/71f2d2253310512e108567f1d29fba66bda9bafa.

Creating this issue so @mmlr remembers to trigger a ca_root_certificates rebuild once the upgrade is done.

**Comment by pulkomandy** [comment]
Should we tag a new release of haikuporter?
