### ISSUE TITLE
PGO support

### ISSUE THREAD

**Issue by cb88** [haikuports/haikuporter#171]
It would be nice if HaikuPorter could implement building a package, running it with some profiling workload, probably an optional tarball of data + script? Then support passing that to a second real build.

This might be useful for speeding up various packages in Haiku. Including the kernel (there are examples of PGO being implemented in the Linux kernel in the past) . 

So goals? Profiling libraries and applications, like libwebkit and web+, and Mesa, Haiku kernel PGO would be probably more complex and require booting and profiling in QEMU, then extracting the profile data from the disk image and passing it onto a second build?

Binary distribution like what Haiku does is ideal for PGO, as it's mostly an annoyance on source based distros like Gentoo but probably worthwhile when doing a single build for everyone. Probably have a way to disable it for packages only available on master though. https://www.phoronix.com/scan.php?page=article&item=gcc-82-pgo&num=1

**Comment by alaviss** [comment]
The problem here is the "profiling" workload. It's hard to get the right one, which is why PGO isn't used widely, and is more suited for targeted workload.

A better approach is to use LTO, which brings actual universal performance improvements by reducing vtable calls for C++ stuff, and also drastically reduce binary size (which is a nice speed up on it's own).

**Comment by alaviss** [comment]
Extensions like this could be done in HaikuPorts directly if https://github.com/haikuports/haikuports/issues/2541 were ever to be implemented. I'm too busy rn to tackle HaikuPorter.

**Comment by cb88** [comment]
LTO and PGO can be done simultaneously... LTO is a completely separate issue separate issue. 

I agree though that LTO is more universal I think you have to be careful to not unintentionally optimize away stiff though... With LTO.

**Comment by alaviss** [comment]
Yes, but see my comment above:

> The problem here is the "profiling" workload. It's hard to get the right one, which is why PGO isn't used widely, and is more suited for targeted workload.

It's also worth noting that the instrumentation phase is _really_ slow, and I don't know if it even works on Haiku.

**Comment by cb88** [comment]
There are two types of profiling that I am aware of the compiler instrumented version should just work. 

Creating a profiling workload isn't hard it's tedious... but probably something that could be done by newer developers as introductory tasks, add workload test compare, modify workload retest etc... 

Yes you could hack it into BUILD() but.. then you can't turn it on and off for master vs release builds.

**Comment by waddlesplash** [comment]
I agree with leorize, this is really not a HaikuPorter issue and should be done by individual applications outside of the ports tree.

**Comment by cb88** [comment]
He didn't say that *at all*

**Comment by cb88** [comment]
Because while that is perfect fine... It means it's always enabled ... Haikuporter needs a switch to disable pgo right?

I suppose to that could just be an environment variable though.... In which case close away? Sorry I got a bit grumpy :/ just closing my ticket with no resolution in my mind at least bothered me a bit.

**Comment by waddlesplash** [comment]
> Because while that is perfect fine... It means it's always enabled ... Haikuporter needs a switch to disable pgo right?

If it's at the recipe level, HaikuPorter will know nothing about it and there should not be a flag to affect it.

**Comment by waddlesplash** [comment]
> Yes which is what I was getting at in the latter half of my comment.... you could get around the lack of a flag with an environment variable I guess... though I'm not sure where you'd define it so the recipe would see it?

Recipes are self-contained, you cannot modify their execution externally. So either a recipe has PGO, or it does not, there will not be runtime switching. This is intentional on the part of recipe design; if you need two versions of the same software, make two recipes.

**Comment by cb88** [comment]
Yeah I see what you mean. As the recipe also has information about where the package builds etc in it.... 
Which would almost certainly be different for many packages with PGO. Unfortunately it isn't as simple as just symlinking the recipe with a different name because of that as well.

**Comment by waddlesplash** [comment]
We follow the Portage layout but are much more like Debian in terms of repository management, yes.



Um, why would the paths be different under PGO?

**Comment by cb88** [comment]
Oh well I was thinking ... what if you just wrote a recipe that supports PGO but you want to also support building without then just symlink the recipe without PGO in the name and check if the recipe name has PGO in it inside the recipe. The only additional burden would be recreating the symlink at updates. ( $portName would be the right variable for that?)

Generally a non PGO build is likely a subset of what you need to do for PGO anyway...  just do the second part of the build without passing in the profiles.

Not sure what I was going on about though otherwise i think I was tired and imagined an roadblock to doing that!
