### ISSUE TITLE
HaikuPorter dependency resolution can't tolerate sub-packages requring other sub-packages

### ISSUE THREAD

**Issue by waddlesplash** [haikuports/haikuporter#173]
See e.g. https://build.haiku-os.org/buildmaster/master/x86_gcc2/?buildrunDir=2256&viewMode=expanded
```
resolving build dependencies failed: requires "postgresql_server == 9.6.10" of package "postgresql_devel-9.6.10" could not be resolved
```
I've temporarily reverted this in https://github.com/haikuports/haikuports/commit/db0ab52cbd6c840c045a5a2c544c1e342e845423 but it really should be fixed.

**Comment by mmlr** [comment]
This is a very common case as this is how devel and base packages are associated, so this mechanism most definitely works.

In this concrete case, you simply do not actually provide postgresql_server as there is no such definition in the PROVIDED_server section. If you compare that with the base package PROVIDES, you find the base provides (postgresql) in the list as the first entry.

There are no implicit per package provides, they always need to be specified.

**Comment by waddlesplash** [comment]
Ah, whoops, I missed that. Why was I able to build it locally then?

**Comment by mmlr** [comment]
No idea, possibly you actually had built a package that provided postgresql_server and that one was available in your local packages?

**Comment by waddlesplash** [comment]
Maybe...? Not sure.
