### ISSUE TITLE
Policy.py: isMissingLibraryDependency() does not find local libraries for symlinked binaries

### ISSUE THREAD

**Issue by nielx** [haikuports/haikuporter#181]
For the [Rust 1.29.0 recipe](https://github.com/haikuports/haikuports/pull/3147/commits) we choose to install the binaries to /boot/develop/tools/rust/bin, with the libraries located at /boot/develop/tools/rust/bin/lib and the binaries symlinked to /boot/system/bin. This is because the libraries should not be provided as public dependencies.

The policy checker reports missing libraries violations. The message is printed by [Policy.py#224](https://github.com/haikuports/haikuporter/blob/2e3681a5192b3354c6dee6a720f8d38580b4f1af/HaikuPorter/Policy.py#L224). The issue is that the `dirPath` parameter supplied to this method is the path of the symlink, but not of the actual binary. Ideally it should check for local libraries at the os.paths.realpath path of the executable as well.

I do not have enough knowledge to determine whether or not local libraries should always follow the real path of the executable. I guess that depends on where runtime_loader looks for local libraries.

**Comment by pulkomandy** [comment]
Fixed in https://github.com/haikuports/haikuporter/pull/219.
