### ISSUE TITLE
Haikuporter fails in strict mode if an included library is used

### ISSUE THREAD

**Issue by Begasus** [haikuports/haikuporter#183]
Seems to be the case for latest vala https://github.com/haikuports/haikuports/pull/3679/files#diff-22fa7266629b88069d789b2d662452a5R55
Without it I get "Warning: POLICY ERROR: can't find used library "libvalaccodegen.so""

**Comment by Begasus** [comment]
At linking time this line comes around "-lgmodule-2.0 -lbe -lroot -lglib-2.0 -lintl ../vala/libvala-0.42.la ../codegen/libvalaccodegen.la"

**Comment by Begasus** [comment]
Seems samba for also had the same problem? https://github.com/haikuports/haikuports/pull/1199

**Comment by pulkomandy** [comment]
Fixed in https://github.com/haikuports/haikuporter/pull/219
