### ISSUE TITLE
relax requirement on python version 2.7

### ISSUE THREAD

**Issue by korli** [haikuports/haikuporter#193]
https://www.python.org/doc/sunset-python-2/

**Comment by mmuman** [comment]
A simple thing to help (could have been a GCI task) is to fix print statements (they are function-like now)…

**Comment by kallisti5** [comment]
whoops.. I just made a PR for that :-)

**Comment by kallisti5** [comment]
https://github.com/haikuports/haikuporter/pull/198

**Comment by kallisti5** [comment]
master now targets Python 3.  haikuporter 1.2.3 was tagged as the last release of haikuporter to support Python 2.x
