### ISSUE TITLE
[lint] warn about defined compat not matched in recipe requires

### ISSUE THREAD

**Issue by kallisti5** [haikuports/haikuporter#203]
**Old Dependency**
libcapstone.so.3
PROVIDES=
lib:libcapstone compat >= 3

**User**
REQUIRES=
lib:libcapstone

```
qemu-system-arm 
runtime_loader: Cannot open file libcapstone.so.3: No such file or directory
```

**Current versions of dependencies:**

**Dependency**
libcapstone.so.4
PROVIDES=
lib:libcapstone compat >= 4

haikuporter lint should check for recipes depending on compat versioned libraries and warn when no compat is specified in the requires.

**Comment by waddlesplash** [comment]
We already do this.

Pre-build consistency check report: https://eu.hpkg.haiku-os.org/haikuports/master/x86_64/current/repo_consistency.txt (i.e. these aren't built)

Post-build consistency check report: https://eu.hpkg.haiku-os.org/haikuports/master/x86_64/current/report.txt (i.e if you try to install these packages you'll see those errors).
