### ISSUE TITLE
Policy for deleting/replacing libraries

### ISSUE THREAD

**Issue by pulkomandy** [haikuports/haikuporter#210]
It is annoying when we replace libraries to always have packages left "dangling" for a few months with unsatisfied dependencies. This happened for the updater from ncurses 5 to 6, and for the switch from libjpeg to libjpeg-turbo. No matter the efforts to rebuild all affected packages, there is always something that slips by. Also, there could be packages outside of haikuports depending on libraries and things.

Here is a proposal on how to approach this:
- First, disable only the devel package of the old library. Keep the main package in the repo. This makes sure existing software continues to run
- Second, bump the revisions of other packages and set a version requirement in the recipes to move them to the newer dependency
- Wait some time
- Finally when we're sure no one is using the old lib, finally remove it

This will provide a smoother transition than the current "remove the package, bump some package revisions and hope for the best" approach.

Possibly we need something like debian popcon to gather data about Haiku installations and know who still has some package installed (that should be opt-in for Haiku users, of course, to be enabled in preferences/software repositories, probably)

**Comment by Begasus** [comment]
I think it's about the same idea I had when I created this issue: https://github.com/haikuports/haikuports/issues/5201

**Comment by alaviss** [comment]
I proposed an update procedure some time ago: https://github.com/haikuports/haikuports/issues/2788. Maybe you can extend the procedure to actually handle "sunsetting" of a library properly?

**Comment by pulkomandy** [comment]
Yes, I think that covers most of it already. Lots of discussions and nothing was actually done... oh well.

**Comment by Begasus** [comment]
> Yes, I think that covers most of it already. Lots of discussions and nothing was actually done... oh well.

I don't think nothing has been done, I think most of the issues reported back then were handled, ports not rebuild at that time will still rise to the occasion (libjpeg >= 9) has been done, the ones prior to it that didn't had the requirement and haven't been rebuild will be sure to pop up ...

**Comment by pulkomandy** [comment]
Well on the forums people complained that openjdk is still broken because of libjpeg, and in a ticket here, someone reported that ghc is still broken because of the ncurses change. It's sad to see things decay this way and packages becoming unusable when it would be so simple to keep old lib packages around instead of removing them...

**Comment by Begasus** [comment]
The changes recorded to libjpeg and ncurses reported so far I tried to fix as many as I could, as mentioned on the report at the forum, we are understaffed atm at haikuports, my time is very limited as it is atm (as most of us are)

**Comment by diversys** [comment]
Here's a list of currently broken packages just in case somebody doesn't know about
https://eu.hpkg.haiku-os.org/haikuports/master/repository/x86_64/current/report.txt

**Comment by Begasus** [comment]
@diversys Do you have a list on the ones broken on x86_gcc2?

**Comment by diversys** [comment]
Sure https://eu.hpkg.haiku-os.org/haikuports/master/repository/x86_gcc2/current/report.txt

**Comment by Begasus** [comment]
Should have guessed that ;)
