### ISSUE TITLE
Add "all" wildcard architecture?

### ISSUE THREAD

**Issue by waddlesplash** [haikuports/haikuporter#220]
That is, we should not have to add new architectures (of which riscv and arm64 are coming soon) en masse to packages, or one at a time, but instead they should be enabled automatically based on some wildcard in the ARCHITECTURES. For instance:

```
ARCHITECTURES="all !x86_gcc2"
```

would enable this package for all architectures except gcc2. Similarly, a `?` or `!` would behave as normal when applied to `all`.

**Comment by pulkomandy** [comment]
Can we just change the default if nothing is specified for a given architecture? What even is the default, currently?

If I have architectures set to "x86", does that imply "arm", "?arm" or "!arm"? I'd say "?arm" would be the most logical choice, but "arm" would be the most convenient.

If we do it this way, there is no need to introduce a special keyword "all" or "ALL".

In all cases there has to be special handling of the "any" architecture.

Possibly x86_gcc2 will need a lot of specific casing in recipes too.

Given these two special cases, I would go with this:
- Have a default value for architectures and secondary_architectures, specified in haikuports.conf or hardcoded in haikuports. These would be all archs except "x86_gcc2" and "any" for architectures, and "x86" for secondary architectures.
- Recipes can then specify their own list (architectures="any"), or remove or add a specific architecture to the list (architectures+="x86_gcc2"; architectures -= "arm"). In most cases they don't need to specify anything
- Removal of the notion of untested architectures, which makes no sense when things work that way

This ends up being quite a big change, but can be done progressively. Once haikuports does things this way, we can start simply removing architecture specifications from recipes that just need the default settings

**Comment by mmuman** [comment]
Hmm there are probably some recipes that are not enabled by default for various reasons though… not ready, or using the git HEAD (but those would be disabled as unsafe anyway)…

**Comment by waddlesplash** [comment]
> Given these two special cases, I would go with this:

I think because of the concerns I noted above, and @mmuman's comment here, that we simply cannot go with the implicit strategy. We are going to have recipes (e.g. GCC) where we add multiple versions ahead, and then disable them using `?` or `!`; so we need an `all` keyword if only because we will need to do `?all` or `!all`.

And, well, if we are going to put it in, what is the value of making it implicit instead of explicit? It seems that it would be better so that recipes do not get enabled by default.

**Comment by pulkomandy** [comment]
In what I suggested, it would be implicit only if you don't specify anything at all in the recipe. I used += and -= operators when you want to modify the default value to add/remove things, and you could still use the = operator to have an explicit setting for a given recipe if needed. Or just no architectures line at all, to use the default value.

I find the use of a special "all" architecture more confusing and more verbose (as most recipes would end up with "all !x86_gcc2" or something similar).

Possibly I'm getting used to Yocto/Bitbake at work and importing their ideas here. That's how they would probably handle it.

**Comment by waddlesplash** [comment]
Yes, it would be more verbose, but due to how we enable/disable recipes via ARCHITECTURES, I think that is a good thing and not a downside here.
