### ISSUE TITLE
Skip creation of git repository if a recipe contains no patches or PATCH function

### ISSUE THREAD

**Issue by jmairboeck** [haikuports/haikuporter#248]
This could be a performance improvement for recipes that don't require patching.

For `PATCHES` this could be decided for each source directory separately. If there is a `PATCH()` function, this applies to all sources.

**Comment by pulkomandy** [comment]
The git repository is mainly useful if you want to make changes and get them using --extract-patchset. For applying patches it isn't really needed (this can be done using patch or could be done using quilt or other tools).

You can already use the -G/--no-git-repo option of haikuporter if you don't need a git repo (if you don't plan to do any patching).

**Comment by jmairboeck** [comment]
I think you are right, this can be handled best with the command line option (if I remember to use it ...).

**Comment by pulkomandy** [comment]
Yes, several of the command line flags should also be config options. But it is not so easy with the current architecture to have both, I think
