### ISSUE TITLE
'meson setup <builddir>' fails in recipes

### ISSUE THREAD

**Issue by robxnano** [haikuports/haikuporter#249]
Recipe: https://github.com/haikuports/haikuports/blob/073bae46af6d69fc51db735aa457f1650f7377dc/media-libs/gst_plugins_good/gst_plugins_good-1.22.0.recipe
Log: https://build.haiku-os.org/buildmaster/master/x86_64/logviewer.html?buildruns/8335/builds/79082.log

Although the recipe used the recommended `meson setup build` command, rather than the deprecated `meson build`, the porter failed. The `--wrap-mode=nodownload` argument inserted [here](https://github.com/robxnano/haikuporter/blob/adc25c2375d3ad59b4f1f6874abd0cd56d8a6538/HaikuPorter/ShellScriptlets.py#L354) caused it to interpret `setup` as the name of a directory.

This needs to be fixed since the old syntax will be [removed](https://github.com/mesonbuild/meson/commit/3c7ab542c0c4770241eae149b0d4cd8de329aee0) at some point in the future.

**Comment by korli** [comment]
Pull request?
