### ISSUE TITLE
Using fixCMake doesn't work as expected.

### ISSUE THREAD

**Issue by Begasus** [haikuports/haikuporter#252]
One example is libp8_platform PR: https://github.com/haikuports/haikuports/pull/8301

Using it there ends up with an `empty $developLibDir/cmake`.

**Comment by Begasus** [comment]
Related issue: https://github.com/haikuports/haikuports/issues/8300

**Comment by jmairboeck** [comment]
I think this should be fixed by #281 (and 36f9a136caf81ba981ba06bda8d41f9c5703dcf1).
