### ISSUE TITLE
Using multiple underscores in recipe name/port name doesn't work for secondary architecture (32bit)

### ISSUE THREAD

**Issue by Begasus** [haikuports/haikuporter#270]
Was trying out today to create perl packages for ipc_system_simple and locale_maketext_extract (_x86) and haikuporter reported it wasn't supported.
```
Warning: skipping ipc_system_simple_x86-1.30, as it is unsupported on the target architecture
```
Building it as ipc_systemsimple_x86 doesn't provide a problem, so the extra underscore prevents this from being used.

**Comment by jmairboeck** [comment]
I can't reproduce this. `haikuporter -S ipc_system_simple_x86` worked just fine here. Did you have a typo somewhere in the recipe?

**Comment by Begasus** [comment]
Need to re-check this, the terminal theme package also worked fine ...

**Comment by Begasus** [comment]
Closing as invalid, sorry for the noise :)
