### ISSUE TITLE
Bootstrap builds broken since commit 35a32ad20a9f396625c7e176f7bac155f3e71378

### ISSUE THREAD

**Issue by ilzu** [haikuports/haikuporter#293]
It seems this commit broke bootstrap builds. Didn't investigate that much further but when trying to build a ppc or arm64 bootsteap image it gets to building zlib_bootstrap package and when building it it seems that the wrapper script gets into an infinite recursion when trying to find cmake until it is killed / segfaults. After reverting this commit it works again.

I think the problem is that the function is called cmake and command -v will return that function name instead of searching the cmake binary. Below is a small test case sctipt, try it with bash -x and you'll see that it recurses infinitely, but if you comment out the command -v line and uncomment the which line it finds the cmake and excutes it.

```
#!/bin/bash

cmake()
{
	echo "start"
	CMAKE="/temp/cmake"
	if [ ! -f $CMAKE ]; then
		CMAKE=$(command -v cmake)
		#CMAKE=$(which cmake)
		echo "command -v returns \"$CMAKE\""
	fi
	echo "CMAKE = $CMAKE"
	$CMAKE 
	echo "end"
}

cmake

```

**Comment by jmairboeck** [comment]
I think `type -P` should work too and still not require `which`. Can you test that?

Sorry for the inconvenience!

**Comment by ilzu** [comment]
I tried with -p after submitting the issue, and it seems to work.
