### ISSUE TITLE
haikuporter --get cannot initialize the source tree.

### ISSUE THREAD

**Issue by pulkomandy** [haikuports/haikuporter#68]
Checkout of ports tree not done yet, I wanted to use --get for that purpose, but it fails:
```
/Dev/Haiku/hporter# ./haikuporter --get
Error: The version of the recipe file format used in the ports tree is older than the one supported by haikuporter.
Error: Please upgrade the ports tree.
```

Expected: haikuporter should be able to create the ports tree itself in that case.

**Comment by michaelvoliveira** [comment]
The same here

**Comment by michaelvoliveira** [comment]
Do not install using HaikuDepot
You have to set up Haikuporter by yourself

__Instructions here__
https://github.com/haikuports/haikuports/wiki

**Comment by pulkomandy** [comment]
I know how to get out of this, but still, --get should work to make things simpler.

**Comment by DarkmatterVale** [comment]
This is not only an issue when you install from HaikuDepot, but from github as well. I am looking into this, but I suspect it is because we do not automatically download haikuports
