### ISSUE TITLE
extractDebugInfo should preserve resources

### ISSUE THREAD

**Issue by humdingerb** [haikuports/haikuporter#70]
As explained by Ingo in this [commit comment](https://github.com/haikuports/haikuports/commit/7fce22cf69aed95bd8f73172c0d61d302793a07e#commitcomment-13784509) of Sequitur. Excerpts from it:
> The `defineDebugInfoPackage` shell function (defined in ShellScriptlets.py) records the paths of the files whose debug info shall be extracted. After the `INSTALL` function of the recipe is finished, `packageDebugInfos` is called which in turn calls `extractDebugInfo` for each recorded file path. `extractDebugInfo` is where the extraction of the debug info happens and where the original files are stripped afterwards.

and:

> For the time being `extractDebugInfo` should be adjusted to first check whether the file has resources and, if so, save them before stripping and re-add them afterwards.

**Comment by hannahyp** [comment]
I'd like to fix it. How can I tell if a file has resources?

**Comment by pulkomandy** [comment]
In C++, you would use the BResource class, but in this case you will have to write a shell script.
Maybe the "resattr" tool could be used to extract resources and save them to a temporary file.

**Comment by hannahyp** [comment]
Tried resattr but it didn't seem to work because it doesn't extract resource types like APPV and BBMP. Also tried other res and elf commands, but none of them worked.

**Comment by mmuman** [comment]
There is 'listres'. And 'xres' should be able to copy them all.

**Comment by hannahyp** [comment]
'listres' only lists the types. I can't get it to extract anything. 'xres' extracts everything including non-resource data, so that when I add the extracted .rsrc file back to the binary, it has the same size as its non-stripped version.

I've written a Python function, but it doesn't run in ShellScriplets.py. How can I add Python code to the shell script?

**Comment by pulkomandy** [comment]
This sounds strange, because xres should extract only resource data (and not debug information, which is part of the ELF file itself). Maybe the file(s) you tried this on had lot of resources and not that much debug info?

**Comment by hannahyp** [comment]
I tried with both Pe and PecoRename, and both had the same result. I am writing a shell script to doing it the hard way. I hope to push the code soon.

**Comment by hannahyp** [comment]
To recreate the result I got:

cp Pe Pe.ori
strip -S Pe
ls -l Pe.ori Pe
xres -o Pe.rsrc Pe.ori
xres -o Pe Pe.rsrc
ls -l Pe.ori Pe

Pe.ori and Pe have the exactly the same size now.

**Comment by pulkomandy** [comment]
My interpretation is that these are already stripped and have no debug information, only resources (strip removes both).
You will get different results if the file has debug info and not that much resources (for example try this with a library, like freetype - a version that is not already stripped).

**Comment by hannahyp** [comment]
![xres pecorename](https://cloud.githubusercontent.com/assets/9368722/12376886/219949e4-bcbe-11e5-8022-a677afcb32c7.png)

**Comment by hannahyp** [comment]
I was confused because I had expected that the binary must not have been stripped if it had resources in it, or else we wouldn't have this bug (stripping the binary would also strip the resources) in the first place.
