### ISSUE TITLE
defineDebugInfoPackage not usable for secondary arch builds

### ISSUE THREAD

**Issue by fbrosson** [haikuports/haikuporter#85]
Adding a debuginfo package for a recipe which has:

``` Shell
ARCHITECTURES="!x86_gcc2 x86 x86_64"
SECONDARY_ARCHITECTURES="!x86_gcc2 x86"
```

does not produce a correct package if built for a secondary arch.
If, for example, one adds to [app-cdr/uif2iso](https://github.com/haikuports/haikuports/tree/master/app-cdr/uif2iso):

``` Shell
commandSuffix=$secondaryArchSuffix
commandBinDir=$binDir
if [ "$targetArchitecture" = x86_gcc2 ]; then
        commandSuffix=
        commandBinDir=$prefix/bin
fi
```

and later:

``` Shell
defineDebugInfoPackage uif2iso \
        $commandBinDir/uif2iso
```

then the uif2iso_x86_debuginfo package will depend on uif2iso instead of uif2iso_x86.

And if one appends the **`$secondaryArchSuffix`** to have:

``` Shell
defineDebugInfoPackage uif2iso$secondaryArchSuffix \
        $commandBinDir/uif2iso
```

then the dependency is OK but the name of the hpkg file is wrong because it starts with
**`uif2iso_x86_x86_debuginfo`**

**Comment by fbrosson** [comment]
There is, however, a simple workaround 
```Shell
defineDebugInfoPackage uif2iso \
	$commandBinDir/uif2iso
if [ -n "$secondaryArchSuffix" ]; then
	REQUIRES_debuginfo="
		uif2iso$secondaryArchSuffix == $portVersion base
		"
fi
```

**Comment by waddlesplash** [comment]
I think @KapiX fixed this?

**Comment by KapiX** [comment]
Yes.
