### ISSUE TITLE
defineDebugInfoPackage may produce an incorrect PROVIDES_debuginfo

### ISSUE THREAD

**Issue by fbrosson** [haikuports/haikuporter#86]
If **`defineDebugInfoPackage`** is invoked to produce a debuginfo package that contains targets having dashes in their names, then the build fails.
Take, for example, **`soxr-0.1.1.recipe`** in [media-libs/soxr](https://github.com/haikuports/haikuports/tree/master/media-libs/soxr).

The following works but does not include debug info for **`libsoxr-lsr.so`**:

``` Shell
defineDebugInfoPackage soxr $libDir/libsoxr.so.0.1.0
```

The following does not work:

``` Shell
defineDebugInfoPackage soxr $libDir/libsoxr.so.0.1.0 $libDir/libsoxr_lsr.so.0.1.9
```

The following does not work either:

``` Shell
defineDebugInfoPackage soxr $libDir/libsoxr.so.0.1.0 $libDir/libsoxr-lsr.so.0.1.9
```

The following works and is complete, but it requires a dirty hack:

``` Shell
defineDebugInfoPackage soxr $libDir/libsoxr.so.0.1.0 $libDir/libsoxr-lsr.so.0.1.9
PROVIDES_debuginfo="
    soxr${secondaryarchsuffix}_debuginfo = $portVersion
    debuginfo:libsoxr.so.0.1.0(soxr$secondaryarchsuffix) = $portVersion
    debuginfo:libsoxr_lsr.so.0.1.9(soxr$secondaryarchsuffix) = $portVersion
    "
```

The following works and is complete, but it requires a small hack:

``` Shell
defineDebugInfoPackage soxr $libDir/libsoxr.so.0.1.0 $libDir/libsoxr-lsr.so.0.1.9
PROVIDES_debuginfo="
    `echo "$PROVIDES_debuginfo" | sed s/libsoxr-lsr/libsoxr_lsr/`
    "
```

Reminder: if you build for a secondary arch then you need an additional hack, as explained in https://github.com/haikuports/haikuporter/issues/85:

``` Shell
REQUIRES_debuginfo="
    soxr$secondaryArchSuffix == $portVersion base
    "
```

**Comment by KapiX** [comment]
Fixed in 9b910e2f9ef289b4d2958de37cf15b51d6236622.
