### ISSUE TITLE
tarfile does not handle unicode in filenames

### ISSUE THREAD

**Issue by mmuman** [haikuports/haikuporter#93]
The attempted 2.3 recipe for bash_completion (commit ca2d83a in HP) triggers this in haikuporter due to tarfile not handling unicode:
```
'ascii' codec can't decode byte 0xc3 in position 44: ordinal not in range(128)
```
The tarball contains funky filenames…

**Comment by korli** [comment]
dos2unix-7.3.1 seems to be also affected.

**Comment by pulkomandy** [comment]
I think I already fixed this with https://github.com/haikuports/haikuporter/commit/94f5931dcd3ffed3e4f8620b7f6100b16d598d80 ? Which version of haikuporter are you running?

Sample of it working fine with dos2unix: http://pulkomandy.tk/~pulkomandy/output/builds/2709.log

**Comment by mmuman** [comment]
No because it's an xz compressed tar, so it's not handled by the same codepath.

**Comment by pulkomandy** [comment]
Oh, ok. I see an opportunity for factoring out this code for handling tar files there.

**Comment by mmuman** [comment]
Ok, it looks like tarfile handles xz in python3. I'll try to rewrite the code to first test is_tarfile and fallback.

**Comment by pulkomandy** [comment]
We're stuck with Python 2 at least until the port of Python 3 to Haiku is a little more complete (it builds, but some of the core modules are missing).
