### ISSUE TITLE
Add optional KEYWORDS variable

### ISSUE THREAD

**Issue by humdingerb** [haikuports/haikuporter#94]
Comma-separated keywords could help finding packages that don't have those keywords used in title, summary or description. Of course, HaikuDepot will have to be taught to look there as well.

**Comment by mmuman** [comment]
I still have work in progress somewhere about adding keywords to the app binary itself and using queries for the Deskbar menu, if someone wants to look at it.
At least the base port folder (gentoo category) should be mentioned.

**Comment by waddlesplash** [comment]
Yeah, why is HDS creating its own categories and not pulling them directly from HaikuPorts?

**Comment by humdingerb** [comment]
This ticket is really to include a KEYWORDS variable in the recipe, that can be extracted by HDS and searched via HaikuDepot. Not for the packaged binary itself (to be used e.g. for Deskbar categories).
Don't mistake keywors with categories.

@waddlesplash , AFAIK HDS doesn't interface with haikuports directly, but with reposistory files in Haiku's trunk. Those don't contain any category. Also, all the other repos don't have any hierarchy that could be used to help with the automatisation. To have consistent categories, it is part of the curating done at HDS.
Sure, the keywords could be curated there as well, but other than the categories - which should be under a central control - keywords can be part of recipes and the work to fill them can be "outsourced" to the recipe creator.

**Comment by pulkomandy** [comment]
I would handle this completely on HDS side. This is something the community can take care of, and it would avoid updating a package just to add or fix the keywords.

**Comment by humdingerb** [comment]
@pulkomandy , that's a very good point.  Everyone would re-download the updated package otherwise... If nobody has anything to add, I'll close this ticket and open it on the HDS tracker. :)

**Comment by humdingerb** [comment]
Created at HDS bugtracker instead. https://github.com/aplgithub/haikudepotserver/issues/109
